### PR TITLE
[M68K] avoid crash if capstone option CS_OPT_DETAIL is not set

### PR DESCRIPTION
**Pull request by nplanel**
Disassembler must run normaly if the useful CS_OPT_DETAIL option is not set.

Signed-off-by: Nicolas PLANEL <nplanel@gmail.com>

### CODE REVIEW

**Comment by emoon** [comment]
Is it really needed to add checks in each of the build functions? If we just bail out at the start of

```C
m68k_disassemble(...)
```

None of those functions will be called.

**Comment by nplanel** [comment]
Yes it is
As you known
```
m68k_disassemble() call all the callback via g_instruction_table[g_cpu_ir].instruction()
... and all callback call MCInst_setOpcode(g_inst, M68K_INS_XXX);
```

In this minimalist mode, capstone would like only the instruction opcode, group, read/write register, ...

CS_OPT_DETAIL disabled => captsone flields only
CS_OPT_DETAIL enabled => captsone flields + disassembler details

**Comment by emoon** [comment]
Ah yes it still wants the instruction only then it makes sense.

**Comment by emoon** [comment]
Now than I think about it maybe we could wrap the build_init_op and return of info (that pretty much all the build function does) inside a macro and return in there. I'm not a big fan of macros in general as it hides stuff but in this case it would make the code a bit cleaner imo.

**Comment by nplanel** [comment]
So you would like to do like so :
```
#define return_if_no_info(xxx) do { if(!xxx) return; } while(0)

So in the code :
return_if_no_info(build_init_op(opcode, 1, 0));

```
We can do that, but we need to check that we didn't return before MCInst_setOpcode(); like in build_imm()

**Comment by emoon** [comment]
Yeah... Maybe it's better to leave it as is for now.

**Pull request merged**
