### PR TITLE
Python objdump address mode

### PR DESCRIPTION
**Pull request by nplanel**
[python][objdump] add address mode
[python][objdump] fixup invalid / data opcode
[M68K] fix A line and F line decoding
[M68K] fixup cmpm register parsing
[contrib]|python] objdump-m68k add address mode decoding
[M68K] remove unused parametter in SStream_concat()

### CODE REVIEW

**Comment by nplanel** [comment]
After this set, If you agree, we can do the PR :)

**Comment by nplanel** [comment]
I done a lot of testing with the fuzzer AFL without any crash.
Objdump vs capstone diff are not so bad, or could be explained.

May we just need to do a last code cleanup, update test_m68k.c (should have the same output as test_m68k.py)

**Comment by nplanel** [comment]
Any point on your side ?

**Comment by emoon** [comment]
Thank! I will do the PR to Capstone mail later today then.

**Pull request merged**
