### PR TITLE
[M68K] Renaming aim to have consistent naming convetion

### PR DESCRIPTION
**Pull request by nplanel**
Fixup compilation as name are case senistive for most arch ...

Signed-off-by: Nicolas PLANEL <nplanel@gmail.com>

### CODE REVIEW

**Comment by emoon** [comment]
Thanks!

I was going to fix this when doing testing on Linux later on before the PR to the main repro (I mainly code on Mac)

**Comment by nplanel** [comment]
You are welcome
I seen that in the test_m68k :)
Strange, Mac OS X FS is case sensitive, so how do you build ?

**Comment by emoon** [comment]
No, Mac OS X is not case sensitive by default (you can create partitions with it enabled though)

**Comment by emoon** [comment]
I also have another question. I wonder how much you plan to implement? I just want to make sure we aren't doing double work somewhere.

**Comment by nplanel** [comment]
I go to sleep now (AU), but I would like to disassemble/decompile a 680000 code, so until I can make it running :)
I will be very glad If you have time to implement theses mnemonic :
 o ext
 o movem.l A0-A1, -(A7)
 o dbra/dbf

**Comment by emoon** [comment]
Alright. I will focus on those when I get home (currently at work) movem is a bit annoying but will deal with it.

**Comment by emoon** [comment]
ext, dbra/dbcc has now been implemented. Will take a look at movem now.

**Comment by nplanel** [comment]
Thanks for your code :)
I'll try that tonight.
I can help you for the non regression and cleanup as well. I thing we are next a to runnable (68k only) version.
And you will be able to PR capstone !

**Comment by emoon** [comment]
Thanks! I would like to implement all the remaining instructions but also add FPU support before doing the PR to capstone but it's getting closer at least which is nice :)

**Comment by nplanel** [comment]
I think it would be better to focus to a full support/clean/tested authentic 68000 and do the PR ;
We will gain some visibility, and more peoples will reach this sub project :)

**Comment by nplanel** [comment]
Just to put a reminder somewhere
  Before sending the PR:
   o M68K code need to be sync in files : ./bindings/python/test_m68k.py and ./tests/test_m68k.c
      => they should generate exactly the same output (make check)
   o Sync the python binding const file 
      => cd bindings directory ; python2 const_generator.py python ; git add python/capstone/m68k.py ...

**Comment by emoon** [comment]
I disagree. My plan all along was to have 680x0 fairly feature complete. The reason is that if capstone makes a new release I don't want to have "mixed" support in there, I want it fairly complete.

If you look at the remaining instructions in the m68kdasm.c they aren't many and I have implemented most of the non-68k instructions. 

The major group left is FPU which I intend to focus on during the weekend.

**Comment by nplanel** [comment]
Ok, the FPU gap is not so big as well
Focus on FPU implementation this weekend as you proposed, I will continue on the python binding, testing/fix non-reg.
Good night

**Comment by emoon** [comment]
Sounds good! Once again thanks for helping out :)

**Comment by emoon** [comment]
Just wanted to say I have implemented all instructions (except the FPU ones and 020 cpXXX which are weird) which is nice (today I have implemented exg,scc,trap,movec,moves,cpush,cinv and more) I had to add a bunch new registers, one instruction (callm) so your Python impl is likely out of data right now.

**Comment by emoon** [comment]
Good progress in general. This is the current output right now from one of my test programs: https://gist.github.com/emoon/674dbdc5373547366fe5

**Comment by emoon** [comment]
Ok.. So now I want to do some additional testing but as for the C implementation I think it should be quite close to do a PR up to Capstone unless something really bad is found so give it a spin.

**Comment by nplanel** [comment]
Good work !
Unfortunately, I was all the weekend AFK, I just PR the python binding implementation

I will do more testing too, let give us 3/4 days to test and fix issue like #18

**Comment by emoon** [comment]
Sounds good! We will likely find more issues that should be sorted out before the main PR.

**Comment by nplanel** [comment]
Yeah for sure

**Comment by emoon** [comment]
Hey I added you as collaborator on my repro so you can push directly... will make turn arounds a bit faster.

**Pull request merged**
